#!/usr/bin/env sh

# abort on errors
set -e

# build
npm run production

# navigate into the build output directory
cd build_production

git init
git add -A
git commit -m 'deploy'

git push -f git@github.com:csdu/sankalan-2019.git master:gh-pages

cd -
